config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'
  get 'payments/create'

  root 'static_pages#index'

  resources :orders, only: [:index, :show, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :comments

	validates :name, presence: true

	def average_rating
		comments.average(:rating).to_f
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      # The next IF statement checks to see if using a development or produciton environment
      if Rails.env.development?
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      else
        @products = Product.where("name ILIKE ?", "%#{search_term}%")
      end  
    else
      @products = Product.all
    end

    respond_with @products
    #@products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # byebug
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/static_pages/landing_page" }
       # format.html { redirect_to @product, notice: 'Product was successfully created.' }
       # format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
		count          = Product.count
		max_updated_at = Product.maximum(:updated_at).try(:to_s, :number)
		"products/all-#{count}-#{max_updated_at}"
	end
end

app/views/products/_comments.html.erb
<div class="container product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
            	<% if signed_in? && current_user.admin? %>
            		<%= link_to ('<span class="glyphicon glyphicon-ban-circle"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            	<% end %></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>




<div class="container">
	<%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :colour %><br>
    <%= f.text_field :colour, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<div class="container">
  <% if signed_in? %>
    <h4>Add a Review:</h4>
      <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
        <div class="form-group">
          <%= f.label :body, "Comments" %>
          <%= f.text_area :body, class: "form-control", rows: "5" %>
        </div>
        
        <div class="rating bottom-margin"></div>
        <p>
          <%= f.submit "Submit", class: "btn btn-default" %>
        </p>
      <% end %>
  <% end %>
</div>

app/views/products/_product.html.erb
<% cache product do %>
<div class="col-sm-6 col-md-4 col-lg-3">

  <div class="thumbnail">
    <div>
      <%= image_tag(product.image_url, :class => 'listing-img') %>
    </div>
    <div class="caption">
      <h3><%= product.name %></h3>
      <p><%= product.description %></p>
      <p><%= product.colour %></p>
      <hr>
      <h4><%= number_to_currency(product.price.to_d/100) %></h4>
      <p class="btn btn-default"><%= link_to 'Show', product %></p>
      <% if can? :update, @product %>
        <p class="btn btn-default"><%= link_to 'Edit', edit_product_path(product) %></p>
      <% end %>
      <% if can? :destroy, @product %>
      <p class="btn btn-default"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
    </div><!-- End of caption class -->
  </div><!-- End of thumbnail -->
</div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
	
	<div class="page-header">
		<%= link_to 'Back', products_path, :class => "btn btn-default pull-right" %>
		<h1>Editing Products</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3">
		<%= render 'form' %>
		<%= link_to 'Show', @product, :class => "btn btn-default" %>
	</div>
</div>

app/views/products/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="container">
  <h1>Custom Bikes</h1>
  <div class="row">
    <!-- <div class="col-sm-6 col-md-4 col-lg-3"> -->
      <% cache(cache_key_for_products) do %>
        <%= render @products %>
      <% end %>

    <!-- </div> --><!-- End of column -->

  </div><!-- End of row -->

</div><!-- End of first container -->


<br>
<div class="container">
  <% if can? :create, @product %>
  <btn class="btn btn-default">
    <%= link_to 'New Product', new_product_path %>
  </btn>
  <% end %>

</div>

app/views/products/new.html.erb
<div class="container">
	
	<div class="page-header">
		<%= link_to 'Back', products_path, :class => "btn btn-default pull-right" %>
		<h1>New Product</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3">

	<%= render 'form' %>

	</div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container show-product">
<div class="row">
  <div class="col-md-6">
    <% cache @product do %>
    <h1><%= @product.name %></h1>
    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>
    <p>Average Rating: <div class="rated" data-score= "<%= @product.average_rating %>"></div></p>
    <p>
      <strong>Colour:</strong>
      <%= @product.colour %>
    </p>
    <p>
      <strong>Price:</strong>
      <%= number_to_currency(@product.price.to_d/100) %>
    </p>
    <% end %>
    <hr>
    <p>
      <%= form_tag "/payments/create" do %>
        <%= render partial: "shared/stripe_checkout_button" %>
      <% end %>
    </p>
      <% if can? :update, @product %>
        <button class="btn btn-default">
            <%= link_to 'Edit', edit_product_path(@product) %>
          </button>
      <% end %>

      <button class="btn btn-default">
        <%= link_to 'Back', products_path %>
      </button>
  </div><!-- End of first col -->
  <div class="col-md-6">
    <div class="img-responsive">
          <%= image_tag(@product.image_url, class: 'img-thumbnail img-zoom', data_zoom_image: "@product.image_url") %>
    </div>
  </div><!-- End of second col -->

<!-- <p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p> -->




</div><!-- End of row -->

</div><!-- End of container -->

<%= render 'new_comment' %>
<%= render 'comments' %>

app/views/products/test.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="container">
  <h1>Custom Bikes</h1>
  <div class="row">
    <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <div class="thumbnail">
        <div>
          <%= image_tag(product.image_url, :class => 'listing-img') %>
        </div>
        <div class="caption">
          <h3><%= product.name %></h3>
          <p><%= product.description %></p>
          <p><%= product.colour %></p>
          <hr>
          <h4><%= number_to_currency(product.price.to_d/100) %></h4>
          <p class="btn btn-default"><%= link_to 'Show', product %></p>
          <% if can? :update, @product %>
            <p class="btn btn-default"><%= link_to 'Edit', edit_product_path(product) %></p>
          <% end %>
          <% if can? :destroy, @product %>
          <p class="btn btn-default"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>
        </div><!-- End of caption class -->
      </div><!-- End of thumbnail -->
    </div><!-- End of column -->
    <% end %>

  </div><!-- End of row -->

</div><!-- End of first container -->


<br>
<div class="container">
  <% if can? :create, @product %>
  <btn class="btn btn-default">
    <%= link_to 'New Product', new_product_path %>
  </btn>
  <% end %>

</div>